name: Scrape Komik Single Genre

on:
  workflow_dispatch:
    inputs:
      genreTarget:
        description: 'Ketik nama genre yang mau di-scrape (contoh: Action, Romance, Isekai, Magic)'
        required: true
        default: 'Action'

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # Menjalankan script dengan menyisipkan parameter genre dari input ke dalam Environment Variable
      - name: Run Scraper untuk Genre ${{ github.event.inputs.genreTarget }}
        env:
          TARGET_GENRE: ${{ github.event.inputs.genreTarget }}
        run: node index.js

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update data genre: ${{ github.event.inputs.genreTarget }}"
          branch: main # Ganti 'master' jika default branch-mu adalah master
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
